pluginGroup=com.deepseek.plugin
pluginName=DeepSeek Inline Completion
pluginVersion=0.1.5

pluginSinceBuild=241
pluginUntilBuild=241.*

platformVersion=2024.1

org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
kotlin.stdlib.default.dependency=false
org.gradle.configuration-cache=false
org.gradle.caching=true